### PR TITLE
Create script for packaging deb file

### PR DESCRIPTION
**Pull request by myii**
### Commit message
* Replacing copy-paste of commands from:
    - https://github.com/aegif/CmisSync/wiki/Packaging/7867cee43c3f92895b870a43ae6ef58420ba2556

### Summary
* `USR_PREFIX` variable at top - if ever moving to installations to `/usr` instead of `/usr/local` - just have to change in this one place
* In preparation for destruction of `ubuntu-mono-*` icons, the relevant `rsync` lines have been included but commented out - these are to be removed when the superfluous icons are removed

### Upon merge (if accepted)
* Wiki page needs to be updated to use this script instead
* Note: script can be run from any directory, not just the `build` directory - up to you if you want to `cd build` first or not - but all work will be done in the `build` directory and the deb will be found there after a successful run

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Very nice!
I will use it as soon as possible.

**Comment by myii** [comment]
That's good, I've just gone ahead and updated the wiki - the [Linux DEB] section is no longer so dominant!  Maybe that's a bad thing... makes us look like we're not as important!

**Comment by myii** [comment]
The fix for this should be as simple as modifying the `Depends` in `build/DEBIAN/control`:

From: `Depends: mono-runtime (>= 3.2.8)`
To: `Depends: mono-runtime (>= 3.2.8), libmono-sqlite4.0-cil`

However, there are some problems... can't build newest version of CmisSync on my Ubuntu system.  Have gone through the commits and here are at least two sets of changes that are causing compilation errors.

### 76946b2 (PR #580)
```
...
./../ControllerBase.cs(426,17): error CS0246: The type or namespace name `MissingFolderDialog' could not be found. Are you missing an assembly reference?
./../ControllerBase.cs(427,17): error CS0841: A local variable `dialog' cannot be used before it is declared
./../ControllerBase.cs(428,21): error CS0841: A local variable `dialog' cannot be used before it is declared
./../ControllerBase.cs(450,26): error CS0841: A local variable `dialog' cannot be used before it is declared
./../ControllerBase.cs(458,26): error CS0841: A local variable `dialog' cannot be used before it is declared
...
Compilation failed: 5 error(s), 20 warnings
```

### edb5439 (PR #581)
```
...
./Sync/SynchronizedFolder.cs(196,32): error CS0246: The type or namespace name `CmisMissingSyncFolderException' could not be found. Are you missing an assembly reference?
./Sync/SynchronizedFolder.cs(438,39): error CS0246: The type or namespace name `CmisMissingSyncFolderException' could not be found. Are you missing an assembly reference?
...
Compilation failed: 2 error(s), 11 warnings
```

The latest code is still affected (at least) by this last error.

**Comment by nicolas-raoul** [comment]
Sorry for the late answer, the problem is that `MissingFolderDialog` was implemented without considering Mac/Linux.

I reverted it [here](https://github.com/aegif/CmisSync/commit/c715a3e9748b230d4697582830cd044983687e8f) for Mac, and I guess the same kind of thing needs to be done for Linux?

**Comment by myii** [comment]
### c715a3e
Still not able to compile with this commit:
```
...
./Sync/SynchronizedFolder.cs(196,32): error CS0246: The type or namespace name `CmisMissingSyncFolderException' could not be found. Are you missing an assembly reference?
./Sync/SynchronizedFolder.cs(437,39): error CS0246: The type or namespace name `CmisMissingSyncFolderException' could not be found. Are you missing an assembly reference?
Compilation failed: 2 error(s), 11 warnings
```
* This is the same error as shown with `edb5439` above
* The last commit I can get to compile is `70e0c95`, one before `76946b2` that I've also shown above
* Can also get commit `b4243a5` to compile -- so regression has been introduced with the merging of #580 and possibly compounded with #581
